#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-ttp229-keybad
#
# --------------------------------------------------------------------------

# --- defaults used during installation   ----------------------------------

# --- basic packages   ------------------------------------------------------

PACKAGES=""
if [ -n "$PACKAGES" ]; then
  apt-get update
  apt-get -y install $PACKAGES
fi

# --- install specific files   ----------------------------------------------

rand="$RANDOM"
if [ -f /etc/ttp229-keypad.conf ]; then
  # save current configuration
  mv /etc/ttp229-keypad.conf /etc/ttp229-keypad.conf.$rand
fi

for f in `find $(dirname "$0")/../files/ -type f`; do
  cp "$f" "${f#*files}"
  chown root:root "${f#*files}"
done
chmod 755 /usr/local/sbin/ttp229-reader.py
chmod 644 /etc/ttp229-keypad.conf
chmod 644 /etc/systemd/system/ttp229-keypad.service

# restore old configuration
if [ -f /etc/ttp229-keypad.conf.$rand ]; then
  mv -f /etc/ttp229-keypad.conf /etc/ttp229-keypad.conf.new
  mv /etc/ttp229-keypad.conf.$rand /etc/ttp229-keypad.conf
  echo -e "\nnew version of configuration file: /etc/ttp229-keypad.conf.new"
fi

# --- activate service   ----------------------------------------------------

systemctl enable ttp229-keypad.service

# --- final configuration is manual   ---------------------------------------

echo -e "\n### Please edit /etc/ttp229-keypad.conf and start ttp229-keypad.service"
